task:
  name: "binary-classification"
  metrics:
    train: ["loss", "accuracy"]
    eval: ["accuracy", "precision", "recall", "f1-score"]
  log:
    log_step: 100
    log_dir: "./task/rusted_classification/logs"
    save: "./task/rusted_classification/ckpts"

data:
  format: "flow_from_directory"
  source: "src/rusted_bolt"
  image_size: 256

model:
  module: "models.classifiers.binary.resnet.ResnetBinary" # model arch
  pretrain: None
  optimizer:
    module: "torch.optim.Adam" # optimizer module
    lr: 0.001
    scheduler: 
      module: "torch.optim.lr_scheduler.ReduceLROnPlateau" # Lr scheduler module
      patience: 5
      factor: 0.15
  criterion: BCELoss # Model criterion
  save: "./task/rusted_classification/ckpts"
  taskname: "rusted_classification"
    